apiVersion: v1
kind: Service
metadata:
  name: learnerreport-frontend
spec:
  selector:
    app: learnerreport-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: learnerreport-backend
spec:
  selector:
    app: learnerreport-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
